#+TITLE: emacs.d
#+AUTHOR: James Conroy-Finn
#+EMAIL: james@logi.cl
#+STARTUP: showall
#+OPTIONS: toc:2 num:nil ^:nil
#+LINK: cask https://github.com/cask/cask
#+LINK: pallet https://github.com/rdallasgray/pallet
#+LINK: cask-fetchers https://github.com/cask/cask/blob/1b012ab26b79cf1af9da9360447382f01162e266/cask.el#L180

* Getting Started

  First things first, we need to setup load paths and get any packages
  that don't live in ELPA installed. For convenience, this is handled
  by [[pallet][Pallet]] and [[cask][Cask]].

** Installing Cask

   Installing [[cask][Cask]] can be done via a provided installation script, or
   via Homebrew.

   #+begin_src sh :tangle no
     curl -fsSkL https://raw.github.com/cask/cask/master/go | python
   #+end_src

   My preferred method is to clone the Cask repository and update my
   ~$PATH~.

   #+begin_src sh :tangle no
     [[ -d ~/.cask ]] ||
       git clone git://github.com/cask/cask.git ~/.cask
   #+end_src

** Benchmarks

   In order to keep track of how expensive each piece of our Emacs
   configuration is, we measure ~require~.

   #+begin_src emacs-lisp :tangle init.el :comments link
     (defun jcf/time-subtract-millis (b a)
       (* 1000.0 (float-time (time-subtract b a))))

     (defvar jcf/require-times nil
       "A list of (FEATURE . LOAD-DURATION). LOAD-DURATION is the time
       taken in milliseconds to load FEATURE.")

     (defadvice require
       (around build-require-times (feature &optional filename noerror) activate)
       "Note in `jcf/require-times' the time taken to require each feature."
       (let* ((already-loaded (memq feature features))
              (require-start-time (and (not already-loaded) (current-time))))
         (prog1
             ad-do-it
           (when (and (not already-loaded) (memq feature features))
             (add-to-list 'jcf/require-times
                          (cons feature
                                (jcf/time-subtract-millis (current-time)
                                                                require-start-time))
                          t)))))
   #+end_src

** Dependencies

   Cask supports installing dependencies via the main package archives
   and ~package.el~, and importantly will clone packages from
   repository URLs.

   When installing via a repository the format we need to use is as
   follows:

   #+begin_src emacs-lisp :tangle no
     (depends-on name fetcher url)
   #+end_src

   To fetch an imaginary package called ~bicycle~ via Git you could
   use the following incantation of ~depends-on~:

   #+BEGIN_SRC emacs-lisp :tangle no
     (depends-on "bicycle" :git "git://github.com/bicycle/bicycle.git")
   #+END_SRC

   ~fetcher~ must be one of the values in [[cask-fetchers][~cask-fetchers~]], which at
   the time of writing consists of:

   - :bzr
   - :cvs
   - :darcs
   - :git
   - :hg
   - :svn

   There are two open issues related to installing Org using Cask
   related to the following issues.

   - https://github.com/cask/cask/issues/169
   - https://github.com/cask/cask/issues/206

   Essentially, the issue is that packages that are already installed
   are ignored, regardless of where they came from. This means Org
   mode, which comes shipped with Emacs won't be installed.

   The workaround according to #169 is to install ~org-plus-contrib~.

   #+begin_src emacs-lisp :tangle Cask :comments link
     (source gnu)
     (source melpa)
     (source org)

     (depends-on "ace-jump-mode")
     (depends-on "ag")
     (depends-on "anzu")
     (depends-on "auto-compile")
     (depends-on "bind-key")
     (depends-on "bug-reference-github")
     (depends-on "bundler")
     (depends-on "cask")
     (depends-on "cider")
     (depends-on "cl-lib-highlight")
     (depends-on "clj-refactor")
     (depends-on "cljsbuild-mode")
     (depends-on "clojure-mode")
     (depends-on "coffee-mode")
     (depends-on "company")
     (depends-on "company-go")
     (depends-on "company-inf-ruby")
     (depends-on "crontab-mode")
     (depends-on "css-eldoc")
     (depends-on "csv-mode")
     (depends-on "csv-nav")
     (depends-on "darcsum")
     (depends-on "dash")
     (depends-on "dash-at-point")
     (depends-on "diff-hl")
     (depends-on "diminish")
     (depends-on "dired+")
     (depends-on "drag-stuff")
     (depends-on "dsvn")
     (depends-on "editorconfig")
     (depends-on "eldoc-eval")
     (depends-on "elein")
     (depends-on "elisp-slime-nav")
     (depends-on "erlang")
     (depends-on "evil")
     (depends-on "evil-exchange")
     (depends-on "evil-indent-textobject")
     (depends-on "evil-jumper")
     (depends-on "evil-leader")
     (depends-on "evil-matchit")
     (depends-on "evil-nerd-commenter")
     (depends-on "evil-numbers")
     (depends-on "evil-surround")
     (depends-on "evil-visualstar")
     (depends-on "exec-path-from-shell")
     (depends-on "expand-region")
     (depends-on "f")
     (depends-on "feature-mode")
     (depends-on "fill-column-indicator")
     (depends-on "flycheck")
     (depends-on "flycheck-cask")
     (depends-on "flycheck-haskell")
     (depends-on "flycheck-hdevtools")
     (depends-on "frame-restore")
     (depends-on "fullframe")
     (depends-on "ggtags")
     (depends-on "gh")
     (depends-on "ghci-completion")
     (depends-on "git-blame")
     (depends-on "git-commit-mode")
     (depends-on "git-messenger")
     (depends-on "git-rebase-mode")
     (depends-on "gitconfig-mode")
     (depends-on "github-browse-file")
     (depends-on "gitignore-mode")
     (depends-on "gnuplot")
     (depends-on "go-mode")
     (depends-on "google-this")
     (depends-on "goto-chg")
     (depends-on "guide-key")
     (depends-on "haml-mode")
     (depends-on "haskell-mode")
     (depends-on "hi2")
     (depends-on "highlight-escape-sequences")
     (depends-on "highlight-symbol")
     (depends-on "hippie-expand-slime")
     (depends-on "hl-sexp")
     (depends-on "htmlize")
     (depends-on "ibuffer-vc")
     (depends-on "idle-highlight-mode")
     (depends-on "ido")
     (depends-on "ido-ubiquitous")
     (depends-on "ido-vertical-mode")
     (depends-on "idomenu")
     (depends-on "inf-ruby")
     (depends-on "ipretty")
     (depends-on "js-comint")
     (depends-on "js2-mode")
     (depends-on "json-mode")
     (depends-on "jsx-mode")
     (depends-on "key-chord")
     (depends-on "less-css-mode")
     (depends-on "lively")
     (depends-on "lua-mode")
     (depends-on "macrostep")
     (depends-on "magit")
     (depends-on "magit-svn")
     (depends-on "markdown-mode")
     (depends-on "mmm-mode")
     (depends-on "move-dup")
     (depends-on "multiple-cursors")
     (depends-on "mwe-log-commands")
     (depends-on "org" :git "git://orgmode.org/org-mode.git")
     (depends-on "org")
     (depends-on "org-fstree")
     (depends-on "org-mac-iCal")
     (depends-on "org-mac-link")
     (depends-on "org-plus-contrib")
     (depends-on "org-pomodoro")
     (depends-on "osx-location")
     (depends-on "page-break-lines")
     (depends-on "pallet")
     (depends-on "pandoc-mode")
     (depends-on "paredit")
     (depends-on "paredit") ; Redshank requires paredit
     (depends-on "php-mode")
     (depends-on "popwin")
     (depends-on "prodigy")
     (depends-on "project-local-variables")
     (depends-on "projectile")
     (depends-on "rainbow-delimiters")
     (depends-on "rainbow-mode")
     (depends-on "redshank")
     (depends-on "regex-tool")
     (depends-on "rinari")
     (depends-on "robe")
     (depends-on "rspec-mode")
     (depends-on "ruby-compilation")
     (depends-on "ruby-hash-syntax")
     (depends-on "ruby-mode")
     (depends-on "s")
     (depends-on "sass-mode")
     (depends-on "scratch")
     (depends-on "scss-mode")
     (depends-on "session")
     (depends-on "skewer-less")
     (depends-on "skewer-mode")
     (depends-on "slamhound")
     (depends-on "slim-mode")
     (depends-on "slime")
     (depends-on "slime-company")
     (depends-on "smartparens")
     (depends-on "smarty-mode")
     (depends-on "smex")
     (depends-on "sql-indent")
     (depends-on "string-utils")
     (depends-on "switch-window")
     (depends-on "tagedit")
     (depends-on "textile-mode")
     (depends-on "tidy")
     (depends-on "typed-clojure-mode")
     (depends-on "undo-tree")
     (depends-on "unfill")
     (depends-on "use-package")
     (depends-on "vc-darcs")
     (depends-on "web-mode")
     (depends-on "wgrep")
     (depends-on "wgrep-ag")
     (depends-on "whitespace-cleanup-mode")
     (depends-on "whole-line-or-region")
     (depends-on "yagist")
     (depends-on "yaml-mode")
     (depends-on "yari")
     (depends-on "yasnippet")
     (depends-on "zenburn-theme")

   #+end_src

   To generate the Cask file for the first time you need to run
   ~org-babel-tangle~ from this file.

* init.el

  Our ~init.el~ needs to pull in the packages installed by [[cask][Cask]] before
  we kick things off.

  #+begin_src emacs-lisp :tangle init.el :comments link
    (require 'cask "~/.cask/cask.el")
    (cask-initialize)
    (require 'pallet)
  #+end_src

  With all of our packages available we can start configuration. To
  keep things manageable configuration is split up into a number of
  files.

** OS X

   There are a number of packages and configurations that only make
   sense on OS X. Although I don't use Emacs on Linux very often, and
   never on Windows it makes sense to ensure Emacs will run in these
   environments.

   #+begin_src emacs-lisp :tangle init-ubiquitous.el :comments link
     (defconst *is-a-mac* (eq system-type 'darwin))
   #+end_src

** Load Org files

  To give you an idea of why, my original literate Emacs config racked
  up over 3000 lines in a single Org file.

  #+begin_src emacs-lisp :tangle init.el :comments link
    (defvar jcf/config-dir
      (file-name-directory (or load-file-name (buffer-file-name))))

    (defun jcf/load-org (s)
      (org-babel-load-file (expand-file-name (format "init-%s.org" s)
                                             jcf/config-dir)))

    (add-hook
     'after-init-hook
     (lambda ()
       (jcf/load-org "defuns")
       (jcf/load-org "genesis")
       (jcf/load-org "ubiquitous")
       (jcf/load-org "presentation")
       (jcf/load-org "evil")
       (when *is-a-mac*
         (jcf/load-org "osx"))
       (jcf/load-org "packages")
       (jcf/load-org "sessions")
       (jcf/load-org "window-management")
       (jcf/load-org "version-control")
       (jcf/load-org "languages")
       (jcf/load-org "locales")))
  #+end_src
